[package]
name = "pytests"
version = "1.0.0"
authors = ["shiro <shiro@usagi.io>"]
edition = "2021"

[lib]
name = "pytests"
crate-type = ["proc-macro"]
proc-macro = true

[dependencies]
syn = "2.0.87"
